<a href="https://colab.research.google.com/github/rakibhossain7/EWU/blob/main/Machine_Learning_DSA5006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Overview & Data Exploration

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
#Creating Series
s = pd.Series([1,2,3,4,5], index=('a', 'b', 'c', 'd', 'e'))
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [58]:
#DataFrame with Multi indexes
row_index = pd.MultiIndex.from_tuples([('Left', 'Football'), ('Right', 'Football'), ('Left', 'Cricket'), ('Right', 'Cricket')])
col_index = pd.MultiIndex.from_tuples([('Amateur', 'Male'), ('Amateur', 'Female'), ('Professional', 'Male'),('Professional', 'Female')])
data = [
    [5, 10, 15, 20], [3, 6, 9, 7], [2,6,4,8], [12, 14, 17, 19]
]
df = pd.DataFrame(data, index=row_index, columns=col_index)
df

               Amateur        Professional
                  Male Female         Male Female
Left  Football       5     10           15     20
Right Football       3      6            9      7
Left  Cricket        2      6            4      8
Right Cricket       12     14           17     19

In [5]:
#Filtering
s_index = s.index
s_value = s.values
print("\n", s_index, s_value)

 Index(['a', 'b', 'c', 'd', 'e'], dtype='object') [1 2 3 4 5]

In [6]:
#Functions
x_bar = s.mean()
x_min = s.min()
x_max = s.max()
x_std = s.std()
print("\n", 'mean:',x_bar, 'min:',x_min, 'max:',x_max, 'standar deviation:',x_std)

 mean: 3.0 min: 1 max: 5 standar deviation: 1.5811388300841898

In [7]:
#Series to DataFrame
s2df = pd.Series([1,2,3,4,5], index=('a', 'b', 'c', 'd', 'e'), name = 'number')
s2df.to_frame()

   number
a       1
b       2
c       3
d       4
e       5

In [8]:
#DataFrame specifying column
df = pd.DataFrame({'a': [1,3,5], 'b': [2,4,6], 'c': [3,6,9]}, columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  3  4  6
2  5  6  9

In [9]:
#DataFrame using a list of Disctionaries
df = pd.DataFrame({'a': [1,3,5], 'b': [2,4,6], 'c': [3,6,9]}, index= ['p', 'q', 'r'])
df

   a  b  c
p  1  2  3
q  3  4  6
r  5  6  9

In [31]:
#Data Merging
stud_info = {'sub_id': ['1', '2', '3', '4', '5'], 'name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung']}
stud_info2 = {'sub_id': ['9', '10', '6', '7', '8'], 'name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty']}
stud_marks = {'sub_id': ['1', '2', '3', '4', '5'], 'marks': [91, 80, 75, 88, 90]}
stud_marks2 = {'sub_id': ['9', '10', '6', '7', '8'], 'marks': [81, 80, 75, 88, 90]}
batch301 = pd.DataFrame(stud_info, columns = ['sub_id', 'name'])
batch302 = pd.DataFrame(stud_info2, columns = ['sub_id', 'name'])
marks301 = pd.DataFrame(stud_marks, columns = ['sub_id', 'marks'])
marks302 = pd.DataFrame(stud_marks2, columns = ['sub_id', 'marks'])
pd.merge(batch301, marks301, on='sub_id')

  sub_id    name  marks
0      1    Alex     91
1      2     Amy     80
2      3   Allen     75
3      4   Alice     88
4      5  Ayoung     90

In [38]:
pd.concat([batch301, batch302])

  sub_id    name
0      1    Alex
1      2     Amy
2      3   Allen
3      4   Alice
4      5  Ayoung
0      9   Billy
1     10   Brian
2      6    Bran
3      7   Bryce
4      8   Betty

In [55]:
#Data Grouping
raw = {
    'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
    'subject_id': ['sub1', 'sub2', 'sub4', 'sub6', 'sub5'],
    'Marks_scored': [98, 90, 87, 69, 78],
    'Year': [2009, 2010, 2011, 2009, 2010]
}
df = pd.DataFrame(raw)
group = df.groupby('Year')
print(df)
print(group.get_group(2009))

     Name subject_id  Marks_scored  Year
0    Alex       sub1            98  2009
1     Amy       sub2            90  2010
2   Allen       sub4            87  2011
3   Alice       sub6            69  2009
4  Ayoung       sub5            78  2010
Group by Year
    Name subject_id  Marks_scored  Year
0   Alex       sub1            98  2009
3  Alice       sub6            69  2009

In [74]:
df.describe().round()
df.info()
df.cumsum()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('Left', 'Football') to ('Right', 'Cricket')
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   (Amateur, Male)         4 non-null      int64
 1   (Amateur, Female)       4 non-null      int64
 2   (Professional, Male)    4 non-null      int64
 3   (Professional, Female)  4 non-null      int64
dtypes: int64(4)
memory usage: 416.0+ bytes

               Amateur        Professional
                  Male Female         Male Female
Left  Football       5     10           15     20
Right Football       8     16           24     27
Left  Cricket       10     22           28     35
Right Cricket       22     36           45     54

# Covariance Analysis