<a href="https://colab.research.google.com/github/rakibhossain7/EWU/blob/main/Machine_Learning_DSA5006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Overview & Data Exploration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Creating Series
s = pd.Series([1,2,3,4,5], index=('a', 'b', 'c', 'd', 'e'))
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
#DataFrame with Multi indexes
row_index = pd.MultiIndex.from_tuples([('Left', 'Football'), ('Right', 'Football'), ('Left', 'Cricket'), ('Right', 'Cricket')])
col_index = pd.MultiIndex.from_tuples([('Amateur', 'Male'), ('Amateur', 'Female'), ('Professional', 'Male'),('Professional', 'Female')])
data = [
    [5, 10, 15, 20], [3, 6, 9, 7], [2,6,4,8], [12, 14, 17, 19]
]
df = pd.DataFrame(data, index=row_index, columns=col_index)
df

               Amateur        Professional
                  Male Female         Male Female
Left  Football       5     10           15     20
Right Football       3      6            9      7
Left  Cricket        2      6            4      8
Right Cricket       12     14           17     19

In [22]:
#Filtering
s_index = s.index
s_value = s.values
print("\n", s_index, s_value)

 Index(['a', 'b', 'c', 'd', 'e'], dtype='object') [1 2 3 4 5]

In [31]:
#Functions
x_bar = s.mean()
x_min = s.min()
x_max = s.max()
x_std = s.std()
print("\n", 'mean:',x_bar, 'min:',x_min, 'max:',x_max, 'standar deviation:',x_std)

 mean: 3.0 min: 1 max: 5 standar deviation: 1.5811388300841898

In [35]:
#Series to DataFrame
s2df = pd.Series([1,2,3,4,5], index=('a', 'b', 'c', 'd', 'e'), name = 'number')
s2df.to_frame()

   number
a       1
b       2
c       3
d       4
e       5

In [41]:
#DataFrame specifying column
df = pd.DataFrame({'a': [1,3,5], 'b': [2,4,6], 'c': [3,6,9]}, columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  3  4  6
2  5  6  9

In [43]:
#DataFrame using a list of Disctionaries
df = pd.DataFrame({'a': [1,3,5], 'b': [2,4,6], 'c': [3,6,9]}, index= ['p', 'q', 'r'])
df

   a  b  c
p  1  2  3
q  3  4  6
r  5  6  9

In [ ]:
#Data Merging
name = {}